name: Update Wiki from folder
on:
  workflow_dispatch:
  push:
    paths:
      - 'wiki/**'

permissions:
  contents: write

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare wiki content
        run: |
          rm -rf wiki-build
          mkdir -p wiki-build
          cp wiki/*.md wiki-build/
          cp wiki/ru/*.md wiki-build/
          cp wiki/int/*.md wiki-build/

      - name: Publish wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: wiki-build
